### PR TITLE
cleans up PHP example styles

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by tswast** [comment]
Thanks!

**Comment by tswast** [comment]
@bshaffer The PHP linter is failing. https://travis-ci.org/GoogleCloudPlatform/cloud-vision/jobs/127634529 I though I used the same config as php-docs-samples, but maybe not?

**Comment by bshaffer** [comment]
@tswast fixed... I must have added the "newline after file" wrong...

**Comment by tswast** [comment]
LGTM, thank you.

**Pull request merged**
