### PR TITLE
image_content may not be JSON serializable

### PR DESCRIPTION
**Pull request by graeme44**
Had issue that image_content was not JSON serializable - python3.5

### CODE REVIEW

**Comment by graeme44** [comment]
Anyone know where Googlebot is? No cla?

**Comment by tswast** [comment]
Thanks for your contribution! I'm trying it out now.

**Comment by tswast** [comment]
I'm still having an issue running this in Python 3.4. Were any other changes needed to get this working in Python 3? Or should I try to install Python 3.5?

```bash
$ python3 label.py ../../data/label/cat.jpg
Traceback (most recent call last):
  File "label.py", line 78, in <module>
    main(args.image_file)
  File "label.py", line 67, in main
    response = service_request.execute()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 755, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/usr/local/lib/python3.4/dist-packages/googleapiclient/http.py", line 93, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 622, in new_request
    redirections, connection_type)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1120, in request
    headers = self._normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 1088, in _normalize_headers
    return _normalize_headers(headers)
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/usr/lib/python3/dist-packages/httplib2/__init__.py", line 194, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by graeme44** [comment]
@tswast I will have a look at this as soon as I can. Do you have any issues without this change on 3.4? I'm trying to establish if it works out of the box. Will test on 3.4.

**Comment by tswast** [comment]
In 3.4, without this change, I see the "is not JSON serializable" error that I think you encountered. I'll play around with it too to see why I'm getting this new exception with your change.

**Comment by tswast** [comment]
I think I'm bumping into https://github.com/google/google-api-python-client/issues/135

**Comment by tswast** [comment]
Upgrading httplib2 fixed the issue for me.

```$ sudo pip3 install --upgrade httplib2
[sudo] password for swast: 
Downloading/unpacking httplib2 from https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.2.tar.gz#md5=bd1b1445b3b2dfa7276b09b1a07b7f0e
  Downloading httplib2-0.9.2.tar.gz (205kB): 205kB downloaded
  Running setup.py (path:/tmp/pip_build_root/httplib2/setup.py) egg_info for package httplib2
    
Installing collected packages: httplib2
  Found existing installation: httplib2 0.8
    Not uninstalling httplib2 at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for httplib2
    
Successfully installed httplib2
Cleaning up...
```

**Comment by graeme44** [comment]
@tswast Great - thanks for this.

**Comment by jerjou** [comment]
Huh. Thinking about this a little more, shouldn't base64-encoding the image guarantee it's json-serializable? This confuses me..

**Comment by tswast** [comment]
@jerjou b64encode returns a byte string, not a unicode string. https://docs.python.org/3.4/library/base64.html#base64.b64encode

**Pull request merged**
