### PR TITLE
Add Go label sample

### PR DESCRIPTION
**Pull request by kaneshin**
Hi, there.

I added a label request sample in encoding base64 image by golang.

### CODE REVIEW

**Comment by tswast** [comment]
Thanks for your contribution! I wasn't able to look at this today. I hope to take a look tomorrow morning.

**Comment by kaneshin** [comment]
Thank you for your reply!
I will add more Go samples of detections like landmark, text, face... if it's merged into this repository. :)

**Comment by tswast** [comment]
LGTM.

It builds and runs successfully and passes [golint](https://github.com/golang/lint) and [go vet](https://golang.org/cmd/vet/). I'll merge, thanks!

**Comment by kaneshin** [comment]
Thx!

**Pull request merged**
