### PR TITLE
allow upload from camera

### PR DESCRIPTION
**Pull request by fahimk**

### CODE REVIEW

**Comment by fahimk** [comment]
I signed it!

**Comment by amygdala** [comment]
Thanks, we'll take a look!  Btw, it looks like your PR contains your API key.  It would be best to remove it, squash, and re-push.

**Comment by fahimk** [comment]
removed the API key, thanks!

**Comment by tswast** [comment]
Thanks! Looks great. I tested it out in the emulator, but had to disable Host GPU setting for some reason. http://stackoverflow.com/a/28975406/101923

**Pull request merged**
