### PR TITLE
Deprecate Go samples.

### PR DESCRIPTION
**Pull request by jerjou**

### CODE REVIEW

**Comment by jerjou** [comment]
Addresses #83

**Comment by broady** [comment]
Could you remove them, instead? Are these files referenced anywhere?

**Comment by jerjou** [comment]
Sure.

**Comment by broady** [comment]
LGTM

**Comment by broady** [comment]
Please submit?

**Comment by jerjou** [comment]
Oi - sorry. Was waiting for travis to pass and then forgot about it.
Turns out it failed while trying to run Go tests. Added a commit to remove the Go tests.
Merging..

**Pull request merged**
