### PR TITLE
Use subtree instead of submodule for java-repo-tools.

### PR DESCRIPTION
**Pull request by tswast**
This way `git clone` just works.

Fixes https://github.com/GoogleCloudPlatform/cloud-vision/issues/56.

### CODE REVIEW

**Comment by amygdala** [comment]
That LGTM. I didn't look through the copied files in detail, but I assume they're known to work already.

**Comment by tswast** [comment]
Thanks!

Mostly it's just copying files from https://github.com/GoogleCloudPlatform/java-repo-tools.

**Comment by jerjou** [comment]
Sorry - jumping on this late. Might want to delete .gitmodules as well.

**Comment by tswast** [comment]
Good call. I thought I did that, but I must have forgot to add it to the commit. I'll send a follow-up PR.

**Pull request merged**
