### PR TITLE
go: update instructions, minor clean up

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by jerjou** [comment]
LGTM

**Comment by broady** [comment]
do not merge (yet)

**Comment by broady** [comment]
This sample doesn't run locally.

```googleapi: Error 403: Project has not activated the vision.googleapis.com API. Please enable the API for project google.com:cloudsdktool (#32555940559)., forbidden
```

Why does it think it should be using the Cloud SDK's project instead of my configured project?

```
$ gcloud config list
[core]
account = <snip>
project = cbro-scratch
[meta]
active_config = default
```

**Comment by tswast** [comment]
If I remember correctly, we have to use JSON API keys for Vision API. @elibixby @amygdala @jerjou to confirm.

I think this sample is looking for the JSON file rather than using the gcloud config. We had to do this in the instructions for the other languages, too.

**Comment by tswast** [comment]
Thank you! LGTM, too.

**Comment by jerjou** [comment]
JSON credentials for a service account, yes. ie this sample doesn't use the config from gcloud - you have to set up application default credentials, either via `gcloud auth activate-service-account` or via the `GOOGLE_APPLICATION_CREDENTIALS` env var. I believe it's in the README already.

**Comment by broady** [comment]
The instructions say that ADC is used. That's not entirely true. Re-worded.

**Comment by jerjou** [comment]
It's not? It should work - did you try using `gcloud auth activate-service-account`?

**Comment by broady** [comment]
Well, the account that's authed must be a service account. How can we change the instructions to reflect that?

**Comment by jerjou** [comment]
IIUC, this is the same for all the apis, when using ADC. When you use `gcloud auth login`, the auth token you get is tied to `gcloud`'s project (via the project's 3LO using its clientid, secret, etc) instead of the environment's project, and it happens that the `gcloud` project doesn't have the vision api enabled. Thus, you'll get an error when calling that api vs others that the project does have enabled. (you'll see this as well, for example, with the monitoring api).

Ergo - this sample does use ADC. It's just that `gcloud auth login` doesn't work, because it uses fundamentally different auth.

**Comment by tswast** [comment]
This should be okay to merge, right?

**Comment by jerjou** [comment]
No objections here.

**Pull request merged**
