### PR TITLE
GSP066-Awwvision: Cloud Vision API from a Kubernetes Cluster(P2==>P3 Conversion)

### PR DESCRIPTION
**Pull request by kalyanipande-tudip**
- Updated the instruction in the worker/Dockerfile for creating the virtual environment as required for the python 3.
- Updated the instruction in the webapp/Dockerfile for creating the virtual environment as required for the python 3.

### CODE REVIEW

**Comment by mylenebiddle** [comment]
@tswast can you review and merge this?

**Comment by seanlubbers1** [comment]
Bump @tswast

**Comment by tswast** [comment]
Thanks for the contribution!

**Comment by seanlubbers1** [comment]
Thanks Tim!

**Pull request merged**
