### PR TITLE
Add Java text sample to READMEs.

### PR DESCRIPTION
**Pull request by tswast**

### CODE REVIEW

**Comment by tswast** [comment]
I forgot to add it to the docs.

**Comment by Kishoreocr** [comment]
Hi,
While using ur code of Java Text sample am not resolving AutoValue_Word in Word class and AutoValue_ImageText in ImageText class.  Am using jdk1.8 and working on STS.

Could you please help me out in this issue.

Thanks in advance.

**Comment by tswast** [comment]
@Kishoreocr I'm not familiar with STS. The pom.xml file should set up the dependencies using Maven. The AutoValue_* classes are generated by the [AutoValue](https://github.com/google/auto/tree/master/value) plugin.

It looks like some configuration may be required to generate a project for IDEs, based on this [blog post](http://grundlefleck.github.io/2014/07/23/configuring-google-autovalue.html).

**Comment by Kishoreocr** [comment]
Thank you for your response.

I have tested from command prompt. its working fine.

My new Question will be as below:
How can we get key value pair of data using cloud vision Text extraction?
here my requirement will be if I give any policy document to text Api, that
will return values like <policyno,1234>,<name,kkkk>
Could you please help me out in this issue.


On Tue, Feb 23, 2016 at 10:42 PM, Tim Swast <notifications@github.com>
wrote:

> @Kishoreocr <https://github.com/Kishoreocr> I'm not familiar with STS.
> The pom.xml file should set up the dependencies using Maven. The
> AutoValue_* classes are generated by the AutoValue
> <https://github.com/google/auto/tree/master/value> plugin.
>
> It looks like some configuration may be required to generate a project for
> IDEs, based on this blog post
> <http://grundlefleck.github.io/2014/07/23/configuring-google-autovalue.html>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/cloud-vision/pull/15#issuecomment-187795963>
> .
>



-- 
Thanks,
M.kishore
mobile: 9703047975

**Pull request merged**
